## **檢查PDF/Excel loading後的結果**

### Read Word file

In [23]:
%pip install -e "C:/Users/ai/Desktop/smithfu/repositories/lazy-tools"

Obtaining file:///C:/Users/ai/Desktop/smithfu/repositories/lazy-tools
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: lazytools
  Building editable for lazytools (pyproject.toml): started
  Building editable for lazytools (pyproject.toml): finished with status 'done'
  Created wheel for lazytools: filename=lazytools-0.1.0-0.editable-py3-none-any.whl size=11179 sha256=3e4a01fa19b43a6043f7250dc41bde3488c359e96f49f7b9403bb453109d08b0
  Stored in directory: C:\Users\ai\AppData\Local\Temp\pip-ephem-wheel-cache-t48w3fqa\wheels\e3\f7\c4\18f8490adda9f0d649905453088067af4d4262c1856ecc4d6c
Successfully built lazytools
Installing collected packages: lazytools
  Attempting uninstall: lazytools
    Found existing installation: lazytools 0.1.0
    Uninstalling lazytools-0.1.0:
      Successfully uninstalled lazytools-0.1.0
Successfully installed lazytools-0.1.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:

# 讓 notebook 能 import src 套件
import os, sys
from pathlib import Path

# sys.path.append(str((Path.cwd().parent).resolve()))
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from pathlib import Path

from docx_xlsx_comparator.adapters.word_table_adapter import WordTableAdapter
from docx_xlsx_comparator.adapters.excel_table_adapter import ExcelTableAdapter
from docx_xlsx_comparator.adapters.pdf_table_adapter import PDFTableAdapter

In [3]:
BASE_DIR   = Path(r"C:\Users\ai\Desktop\smithfu\repositories\lazy-tools\docx_xlsx_comparator")
INPUT_DIR  = BASE_DIR / "input"
OUTPUT_DIR = BASE_DIR / "output"

In [4]:
pdf_path =  INPUT_DIR / r"附件1_115年度農業生產目標-各品項總表(核定版).pdf"
# pdf_path =  INPUT_DIR / r"C:\Users\ai\Desktop\smithfu\repositories\lazy-tools\docx_xlsx_comparator\input\附件1_115年度農業生產目標-各品項總表(核定版).pdf"


print(pdf_path)
pdf_adapter = PDFTableAdapter(pdf_path)
pdf_df = pdf_adapter.load()
# # Note: Maybe there's some newline characters '\n' in the column names, we need to remove them.
# normalized_columns = [col.replace("\n", "") for col in pdf_df.columns]
# word_df.columns = normalized_columns

C:\Users\ai\Desktop\smithfu\repositories\lazy-tools\docx_xlsx_comparator\input\附件1_115年度農業生產目標-各品項總表(核定版).pdf
跳過第 58 頁：目前尚未支援這個表格版型
跳過第 59 頁：目前尚未支援這個表格版型
跳過第 60 頁：目前尚未支援這個表格版型
跳過第 61 頁：目前尚未支援這個表格版型
跳過第 62 頁：目前尚未支援這個表格版型
跳過第 63 頁：目前尚未支援這個表格版型
跳過第 64 頁：目前尚未支援這個表格版型
跳過第 65 頁：目前尚未支援這個表格版型
跳過第 66 頁：目前尚未支援這個表格版型
跳過第 67 頁：目前尚未支援這個表格版型
跳過第 68 頁：目前尚未支援這個表格版型
跳過第 69 頁：目前尚未支援這個表格版型
跳過第 70 頁：目前尚未支援這個表格版型
跳過第 71 頁：目前尚未支援這個表格版型
跳過第 72 頁：目前尚未支援這個表格版型
跳過第 73 頁：目前尚未支援這個表格版型
跳過第 74 頁：目前尚未支援這個表格版型
跳過第 75 頁：目前尚未支援這個表格版型
跳過第 76 頁：目前尚未支援這個表格版型
跳過第 77 頁：目前尚未支援這個表格版型
跳過第 78 頁：目前尚未支援這個表格版型
跳過第 79 頁：目前尚未支援這個表格版型
跳過第 80 頁：目前尚未支援這個表格版型
跳過第 81 頁：目前尚未支援這個表格版型
跳過第 82 頁：目前尚未支援這個表格版型
跳過第 83 頁：目前尚未支援這個表格版型
跳過第 84 頁：目前尚未支援這個表格版型
跳過第 85 頁：目前尚未支援這個表格版型
跳過第 86 頁：目前尚未支援這個表格版型
跳過第 87 頁：目前尚未支援這個表格版型
跳過第 88 頁：目前尚未支援這個表格版型
跳過第 89 頁：目前尚未支援這個表格版型
跳過第 90 頁：目前尚未支援這個表格版型
跳過第 91 頁：目前尚未支援這個表格版型
跳過第 92 頁：目前尚未支援這個表格版型
跳過第 93 頁：目前尚未支援這個表格版型
跳過第 94 頁：目前尚未支援這個表格版型
跳過第 95 頁：目前尚未支援這個表格版型
跳過第 96 頁：目前尚未支援這個表格版型
跳過第 97 頁：目前尚未支援這個表格版型
跳過第 98 頁：目前尚未支援這個表格版型

f

In [5]:
pdf_df

          作物   年度    指標  單位       數值
0     稻米(糙米)  112  種植面積  公頃   222416
1     稻米(糙米)  113  種植面積  公頃   240357
2     稻米(糙米)  112  收穫面積  公頃   222413
3     稻米(糙米)  113  收穫面積  公頃   240284
4     稻米(糙米)  112    產量  公噸  1147898
..       ...  ...   ...  ..      ...
451  香菇(太空包)  113  收穫面積  萬包    19797
452  香菇(太空包)  112    產量  公噸     4275
453  香菇(太空包)  113    產量  公噸     3905
454  香菇(太空包)  112    產值  千元  6423639
455  香菇(太空包)  113    產值  千元  5861708

[456 rows x 5 columns]

### Read Excel file

In [6]:
excel_path =  INPUT_DIR / "115.10.19合併結果.xlsx"
excel_adapter = ExcelTableAdapter(excel_path)
excel_df = excel_adapter.load()

In [7]:
excel_df

      作物   年度    指標  單位      數值
0     香蕉  100    產量  公噸  305740
1     鳳梨  100    產量  公噸  401367
2    柑橘類  100    產量  公噸  556944
3     芒果  100    產量  公噸  169380
4    番石榴  100    產量  公噸  168848
..   ...  ...   ...  ..     ...
643    茶  111  收穫面積  公頃   11821
644   芝麻  112  收穫面積  公頃    1393
645    茶  112  收穫面積  公頃   11994
646   芝麻  113  收穫面積  公頃    1776
647    茶  113  收穫面積  公頃   11783

[648 rows x 5 columns]

### Compare raw value

In [13]:
def select_records(df):
    return df.loc[
        df["作物"].eq("茶")
        & df["年度"].isin([112, 113])
        & df["指標"].isin(["產量", "產值", "種植面積", "收穫面積"])
    ].copy()


pdf_selected = select_records(pdf_df)
excel_selected = select_records(excel_df)

In [14]:
pdf_selected

   作物   年度    指標  單位       數值
72  茶  112  種植面積  公頃    12204
73  茶  113  種植面積  公頃    12078
74  茶  112  收穫面積  公頃    11994
75  茶  113  收穫面積  公頃    11783
76  茶  112    產量  公噸    12350
77  茶  113    產量  公噸    13552
78  茶  112    產值  千元  7282961
79  茶  113    產值  千元  8046741

In [15]:
excel_selected

    作物   年度    指標  單位        數值
313  茶  112    產量  公斤  12350490
315  茶  113    產量  公斤  13552406
321  茶  112    產值  千元   7282961
323  茶  113    產值  千元   8046741
637  茶  112  種植面積  公頃     12204
639  茶  113  種植面積  公頃     12078
645  茶  112  收穫面積  公頃     11994
647  茶  113  收穫面積  公頃     11783

### 對齊資料，再判斷結果

In [18]:
KEYS = ["作物", "年度", "指標"]

result_df = pdf_selected.merge(
    excel_selected,
    on=KEYS,
    how="outer",
    suffixes=("_pdf", "_excel"),
    indicator=True,
    validate="one_to_one",
)

In [19]:
result_df

  作物   年度    指標 單位_pdf   數值_pdf 單位_excel  數值_excel _merge
0  茶  112  收穫面積     公頃    11994       公頃     11994   both
1  茶  112    產值     千元  7282961       千元   7282961   both
2  茶  112    產量     公噸    12350       公斤  12350490   both
3  茶  112  種植面積     公頃    12204       公頃     12204   both
4  茶  113  收穫面積     公頃    11783       公頃     11783   both
5  茶  113    產值     千元  8046741       千元   8046741   both
6  茶  113    產量     公噸    13552       公斤  13552406   both
7  茶  113  種植面積     公頃    12078       公頃     12078   both

In [17]:
def compare_status(row):
    if row["_merge"] == "left_only":
        return "Excel 缺少資料"

    if row["_merge"] == "right_only":
        return "PDF 缺少資料"

    if row["單位_pdf"] != row["單位_excel"]:
        return "單位不同"

    pdf_value = row["數值_pdf"]
    excel_value = row["數值_excel"]

    if (
        pd.isna(pdf_value)
        or pd.isna(excel_value)
        or isinstance(pdf_value, str)
        or isinstance(excel_value, str)
    ):
        return "缺值／標記，暫不比對"

    return "相同" if pdf_value == excel_value else "數值不同"


result_df["比對結果"] = result_df.apply(compare_status, axis=1)

display(result_df.drop(columns="_merge"))

  作物   年度    指標 單位_pdf   數值_pdf 單位_excel  數值_excel  比對結果
0  茶  112  收穫面積     公頃    11994       公頃     11994    相同
1  茶  112    產值     千元  7282961       千元   7282961    相同
2  茶  112    產量     公噸    12350       公斤  12350490  單位不同
3  茶  112  種植面積     公頃    12204       公頃     12204    相同
4  茶  113  收穫面積     公頃    11783       公頃     11783    相同
5  茶  113    產值     千元  8046741       千元   8046741    相同
6  茶  113    產量     公噸    13552       公斤  13552406  單位不同
7  茶  113  種植面積     公頃    12078       公頃     12078    相同